// src/data/ingredients.js

const ingredientsData = [
    { category: 'Proteins', ingredient: 'Chicken Breast', in_stock: true, quantity: 200, unit: 'g', image:'/public/pantry_icons/chicken_breast.png', description: 'Boneless skinless chicken breast is the leanest part of the chicken. It is a white meat that is tender and mild in taste, making it an ideal base for a wide variety of dishes.'},
    { category: 'Proteins', ingredient: 'Chicken Thigh', in_stock: true, quantity: 500, unit: 'g' },
    { category: 'Proteins', ingredient: 'Chicken Wings', in_stock: true, quantity: 300, unit: 'g' },
    { category: 'Proteins', ingredient: 'Mince Chicken', in_stock: true, quantity: 300, unit: 'g', image: '/public/pantry_icons/mince_chicken.png', description: 'Chicken meat that has been finely chopped or processed into a ground form. It is used as a lean substitute for Beef Mince in burgers, meatballs and pasta sauce.' },
    { category: 'Proteins', ingredient: 'Mince Beef', in_stock: true, quantity: 300, unit: 'g' , image: '/public/pantry_icons/mince_chicken.png', description: 'Beef that has been finely chopped or processed into a ground form. It is used in a variety of dishes, including burgers, meatballs, and pasta sauce.' },
    { category: 'Proteins', ingredient: 'Rib Eye', in_stock: true, quantity: 250, unit: 'g' },
    { category: 'Proteins', ingredient: 'Sirloin', in_stock: true, quantity: 250, unit: 'g' },
    { category: 'Proteins', ingredient: 'T-Bone', in_stock: true, quantity: 250, unit: 'g' },  
    { category: 'Proteins', ingredient: 'Pork Chops', in_stock: true, quantity: 300, unit: 'g' },
    { category: 'Proteins', ingredient: 'Pork Loin', in_stock: true, quantity: 300, unit: 'g' },
    { category: 'Proteins', ingredient: 'Pork Ribs', in_stock: true, quantity: 500, unit: 'g' },
    { category: 'Proteins', ingredient: 'Bacon Rashers', in_stock: true, quantity: 300, unit: 'g' },
    { category: 'Proteins', ingredient: 'Pork Sausages', in_stock: true, quantity: 500, unit: 'g' },
    { category: 'Proteins', ingredient: 'Pork Shoulder', in_stock: true, quantity: 500, unit: 'g' },
    { category: 'Proteins', ingredient: 'Pork Belly', in_stock: false, quantity: 0, unit: 'g' },
    { category: 'Proteins', ingredient: 'Salmon', in_stock: true, quantity: 300, unit: 'g' },
    { category: 'Proteins', ingredient: 'Tuna', in_stock: true, quantity: 300, unit: 'g' },
    { category: 'Proteins', ingredient: 'Cod', in_stock: true, quantity: 300, unit: 'g' },
    { category: 'Dairy & Dairy Alternatives', ingredient: 'Milk', in_stock: true, quantity: 1000, unit: 'ml', image: '/public/pantry_icons/milk.png', description: 'Milk is a good source of calcium, protein, and vitamins. It is commonly used in baking and is great for thickening sauces and smoothies.' },
    { category: 'Dairy & Dairy Alternatives', ingredient: 'Greek Yogurt', in_stock: true, quantity: 500, unit: 'g', image: '/public/pantry_icons/greek_yogurt.png', description: 'Greek yogurt is a thicker, creamier version of regular yogurt. It is high in protein and can be used in both sweet and savory dishes.' },
    { category: 'Dairy & Dairy Alternatives', ingredient: 'Cream', in_stock: true, quantity: 500, unit: 'ml' },
    { category: 'Dairy & Dairy Alternatives', ingredient: 'Parmesan', in_stock: true, quantity: 200, unit: 'g' },
    { category: 'Dairy & Dairy Alternatives', ingredient: 'Butter', in_stock: false, quantity: 0, unit: 'g' },
    { category: 'Fruit', ingredient: 'Apples', in_stock: true, quantity: 5, unit: 'units', image: '/public/pantry_icons/apple.png', description: 'Apples are a popular fruit known for their crisp texture and sweet-tart flavor. They are often eaten raw, but can also be used in cooking and baking.' },
    { category: 'Fruit', ingredient: 'Pomegranates', in_stock: false, quantity: 0, unit: 'units', image: '/public/pantry_icons/pomegranate.png', description: 'Pomegranates are a unique fruit with a tough outer skin and juicy seeds inside. They are often used in salads, juices, and desserts.' },
    { category: 'Fruit', ingredient: 'Oranges', in_stock: true, quantity: 10, unit: 'units', image: '/public/pantry_icons/orange.png', description: 'Oranges are a citrus fruit known for their sweet and tangy flavor. They are often eaten fresh or juiced, and are a good source of vitamin C.' },
    { category: 'Fruit', ingredient: 'Pears', in_stock: true, quantity: 3, unit: 'units', image: '/public/pantry_icons/pear.png', description: 'Pears are a sweet and juicy fruit with a soft texture. They can be eaten raw or cooked, and are often used in desserts and salads.' },
    { category: 'Fruit', ingredient: 'Grapes', in_stock: true, quantity: 1, unit: 'g', image: '/public/pantry_icons/grapes.png', description: 'Grapes are small, round fruits that grow in clusters. They can be eaten fresh, dried (as raisins), or used to make wine.' },
    { category: 'Fruit', ingredient: 'Bananas', in_stock: true, quantity: 6, unit: 'units', image: '/public/pantry_icons/banana.png', description: 'Bananas are a tropical fruit known for their sweet flavor and soft texture. They are often eaten raw, but can also be used in smoothies and baked goods.' },
    { category: 'Fruit', ingredient: 'Lemons', in_stock: true, quantity: 1, unit: 'units', image: '/public/pantry_icons/lemon.png', description: 'Lemons are a citrus fruit known for their sour and tangy flavor. They are often used in cooking and baking, and are a good source of vitamin C.' },
    { category: 'Vegetables', ingredient: 'Potatoes', in_stock: true, quantity: 600, unit: 'g', image: '/public/pantry_icons/potato.png', description: 'Potatoes are a starchy vegetable that can be prepared in many ways, including boiling, baking, and frying. They are a staple food in many cultures.' },
    { category: 'Vegetables', ingredient: 'Carrots', in_stock: true, quantity: 100, unit: 'g', image: '/public/pantry_icons/carrot.png', description: 'Carrots are a root vegetable known for their sweet flavor and crunchy texture. They can be eaten raw, cooked, or juiced.' },
    { category: 'Vegetables', ingredient: 'Onions', in_stock: true, quantity: 100, unit: 'g' },
    { category: 'Vegetables', ingredient: 'Garlic', in_stock: true, quantity: 5, unit: 'units' },
    { category: 'Vegetables', ingredient: 'Tomatoes', in_stock: true, quantity: 400, unit: 'g' },
    { category: 'Vegetables', ingredient: 'Cherry Tomatoes', in_stock: true, quantity: 200, unit: 'g' },
    { category: 'Vegetables', ingredient: 'Cucumbers', in_stock: true, quantity: 3, unit: 'units' },
    { category: 'Vegetables', ingredient: 'Bell Peppers', in_stock: true, quantity: 4, unit: 'units' },
    { category: 'Vegetables', ingredient: 'Spinach', in_stock: true, quantity: 500, unit: 'g' },
    { category: 'Vegetables', ingredient: 'Broccoli', in_stock: true, quantity: 500, unit: 'g' },
    { category: 'Vegetables', ingredient: 'Cauliflower', in_stock: false, quantity: 0, unit: 'g' },
    { category: 'Vegetables', ingredient: 'Lettuce', in_stock: true, quantity: 1, unit: 'units' },
    { category: 'Vegetables', ingredient: 'Zucchini', in_stock: true, quantity: 2, unit: 'units' },
    { category: 'Vegetables', ingredient: 'Eggplant', in_stock: true, quantity: 1, unit: 'units' },
    { category: 'Vegetables', ingredient: 'Mushrooms', in_stock: true, quantity: 500, unit: 'g' },
    { category: 'Grains & Starches', ingredient: 'Rice', in_stock: true, quantity: 2, unit: 'g' },
    { category: 'Grains & Starches', ingredient: 'Pasta', in_stock: true, quantity: 1, unit: 'g' },
    { category: 'Grains & Starches', ingredient: 'Quinoa', in_stock: true, quantity: 500, unit: 'g' },
    { category: 'Grains & Starches', ingredient: 'Bread', in_stock: true, quantity: 1, unit: 'slices' },
    { category: 'Grains & Starches', ingredient: 'Tortillas', in_stock: true, quantity: 10, unit: 'units' },
    { category: 'Grains & Starches', ingredient: 'Oats', in_stock: true, quantity: 500, unit: 'g' },
    { category: 'Grains & Starches', ingredient: 'Bulgur', in_stock: true, quantity: 500, unit: 'g' },
    { category: 'Grains & Starches', ingredient: 'Pita Bread', in_stock: true, quantity: 1, unit: 'units' },
    { category: 'Herbs & Spices', ingredient: 'Parsley', in_stock: true, quantity: 1, unit: 'units' },
    { category: 'Herbs & Spices', ingredient: 'Fresh Garlic', in_stock: true, quantity: 5, unit: 'cloves' },
    { category: 'Herbs & Spices', ingredient: 'Cumin', in_stock: true, quantity: 20, unit: 'g' },
    { category: 'Herbs & Spices', ingredient: 'Coriander', in_stock: true, quantity: 1, unit: 'units' },
    { category: 'Herbs & Spices', ingredient: 'Paprika', in_stock: true, quantity: 20, unit: 'g' },
    { category: 'Oils & Condiments', ingredient: 'Olive Oil', in_stock: true, quantity: 500, unit: 'ml' },


    // Add more...
  ];
  
  export default ingredientsData;
  